### ISSUE TITLE
Section on optionally encrypting secrets in database?

### ISSUE THREAD

**Issue by duffn** [joelbutcher/socialstream-docs#3]
Thanks for the package. When I use it, I have been encrypting the secrets in the database with https://github.com/Crudly/Encrypted. It's nice and simple, and only a few changes to the model and migration. 

This is too big of a breaking change to add to the package itself, I think, but I'd add a section to the docs giving people the option of encrypting the secrets, if it's something you'd be interested in.

**Comment by joelbutcher** [comment]
Hey @duffn, thanks for this, encrypting keys is definitely a big win for OAuth. However, since this can be implemented at the discretion of the developer, I think I'd prefer to minimise the unrelated "noise" in the official documentation.

If you have examples, it would be great if you could share them and we could collaborate on a laravel.io or medium.com article?

Thanks!

**Comment by duffn** [comment]
I've made an example repository here with the changes and a detailed README. I'm happy to collaborate on a blog post. https://github.com/duffn/laravel-socialstream-encrypted
